= CMake extensions for CDT =

Additional CMake related functionality for Eclipse CDT.

CDT supports CMake by providing a specific C/C++ project type
that extends the new core build system with a configuration provider
and a very simple property page in the build configuration dialog
offered by the `launch bar`.

link:doc/cdt-build-notes.adoc[Here are some notes] on the CDT `core.build`, with specifics for `cmake`

== The cmakeopts.json file format ==

This is a configuration file used to describe how to call `cmake`:

* define the top-level `CMakeLists.txt`
* define the build directory
* list build configurations and for each one the parameters list

Example:

----
{
  rootCMakeLists : "path/to/CMakeLists.txt",
  buildDirectory : "path/to/build"
  generator: "Ninja",
  buildConfigurations: [
    {
      name: "config_1",
      type : "Debug",
      cmakeArgs : ""
    },
    {
      name: "config_2",
      type : "Release",
      cmakeArgs : ""
    },
    ...
  ]
}
----

The plugin offers an editor for this file (it is registered to open files named `cmakeopts.json`)
and a UI to invoke `cmake` as defined by the configuration file.
